= ESPHome Config
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Asciidoctor_: https://asciidoctor.org/[Asciidoctor]
:ESPHome: https://esphome.io[ESPHome]
:Git: https://git-scm.com/[Git]

image:https://img.shields.io/github/workflow/status/jwillikers/esphome-config/CI/main[GitHub Workflow Status]
image:https://img.shields.io/badge/pre--commit-enabled-brightgreen?logo=pre-commit&logoColor=white[pre-commit, link=https://github.com/pre-commit/pre-commit]

My {ESPHome} configuration for all my ESPHome devices.

== Usage

. Clone the repository.
+
[source,sh]
----
git clone git@github.com:jwillikers/esphome-config.git
----

. Create a `secrets.yaml` file in your ESPHome configuration directory with your WiFi SSID and password.
In addition to these, each device should have it's own password for OTA updates and the fallback WiFi hotspot.
Each device also requires a pre-shared encryption key for communicating securely with the Home Assistant API.
See the https://esphome.io/components/api.html#configuration-variables[Native API - for each device Configuration Variables] section of the ESPHome documentation for details.
Home Assistant will prompt you for the device's key once the device has been updated.
+
.~/.local/share/containers/storage/volumes/esphome-config/_data/secrets.yaml
[source,yaml]
----
# WiFi SSID and password
wifi_ssid: "My Access Point"
wifi_password: "My Password"

# Fallback WiFi Hotspot AP passwords
cloudfree_smart_plug_v2_1_wifi_ap_password: "Ce7Ro2q98asxBUaJbQMb5vszyWGCDoXJ"
cloudfree_smart_plug_v2_2_wifi_ap_password: "QZN43ju2dCj8xPcx4ZQspUgShUxH5r5v"
environment_sensor_wifi_ap_password: "zf4o9r2JheMf8o3FQ5NbC3WtQCDc3fCn"
funhouse_wifi_ap_password: "ZJfjc4bvKefxxBbh8cfcknCNB9SBrf3S"
humidity_sensor_wifi_ap_password: "uBQ5gh8bR2NJ9wGX9zRsGon8A8GvX3tx"
pressure_sensor_wifi_ap_password: "zr3hXkcvCjMAJZhqzp9u7bgJqtB4nbWT"

# Over-The-Air update passwords
cloudfree_smart_plug_v2_1_ota_password: "E4kRh6Yuf4nt4L6Uh9j4QjSGCL445gLv"
cloudfree_smart_plug_v2_2_ota_password: "gNJyLJY3fSf8hBvqyZWCSKWPoQQjsfv5"
environment_sensor_ota_password: "UcuSfsMkJLjS862JYQNWiWi4GdEkj4rp"
funhouse_ota_password: "njnzzVTU9MePQPQ3xoyjs3RZnaJuVaX4"
humidity_sensor_ota_password: "njnzzVTU9MePQPQ3xoyjs3RZnaJuVaX4"
pressure_sensor_ota_password: "3hfedXC8MzQwvandTo7ToJ82H8MRyBG5"

# Pre-shared Home Assistant API encryption keys
cloudfree_smart_plug_v2_1_api_encryption_key: "NKnCdo4g9aBF30g1S1e7Gkcm0d+3OK7zik/Ni2VPFyk="
cloudfree_smart_plug_v2_2_api_encryption_key: "wVBxAjQUPseCDpJ02yWEx0It+mik1YLOR2juooJ9520="
environment_sensor_api_encryption_key: "Ekp5fU6okwQ3a6quNSWYTQY1u3azE11vd3r0rTrj6s0="
funhouse_api_encryption_key: "E7EH9iIVNpRMaYF6VpZ4RjcqnQuECAacDPROQrKevyU="
humidity_sensor_api_encryption_key: "x6KOGUkwi1R8raTu8dtPAawdK+rOxlIMQOZG1PO9OFE="
pressure_sensor_api_encryption_key: "itzs4DA2XGkjAY0Dejiue5igdqOSg7k+aUs4Xsr6M1s="
----

. Copy the contents of the `esphome` directory to your ESPHome configuration directory.
+
[source,sh]
----
cp -r esphome-config/esphome/* ~/.local/share/containers/storage/volumes/esphome-config/_data/
----

== Contributing

Contributions in the form of issues, feedback, and even pull requests are welcome.
Make sure to adhere to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== Open Source Software

This project is built on the hard work of countless open source contributors.
Several of these projects are enumerated below.

* {Asciidoctor_}
* {ESPHome}
* {Git}

== Code of Conduct

Refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct] for details.

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3], a copy of which is provided in the link:LICENSE.adoc[license file].

© 2022 Jordan Williams

== Authors

mailto:{email}[{author}]
