= ESPHome Config
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Asciidoctor_: https://asciidoctor.org/[Asciidoctor]
:ESPHome: https://esphome.io[ESPHome]
:Git: https://git-scm.com/[Git]

image:https://img.shields.io/github/workflow/status/jwillikers/esphome-static-network/CI/main[GitHub Workflow Status]
image:https://img.shields.io/badge/pre--commit-enabled-brightgreen?logo=pre-commit&logoColor=white[pre-commit, link=https://github.com/pre-commit/pre-commit]

My {ESPHome} configuration for all my ESPHome devices.

== Usage

. Clone the repository.
+
[source,sh]
----
git clone git@github.com:jwillikers/esphome-config.git
----

. Create a `secrets.yaml` file in your ESPHome configuration directory with your WiFi SSID and password as well as a password for OTA updates and the fallback WiFi hotspot.
+
.~/.local/share/containers/storage/volumes/esphome-config/_data/secrets.yaml
[source,yaml]
----
wifi_ssid: "My Access Point"
wifi_password: "My Password"
wifi_ap_password: "Another Password"
ota_password: "Yet Another Password"
----

. Copy the contents of the `esphome` directory to your ESPHome configuration directory.
+
[source,sh]
----
cp -r esphome-config/esphome/* ~/.local/share/containers/storage/volumes/esphome-config/_data/
----

== Contributing

Contributions in the form of issues, feedback, and even pull requests are welcome.
Make sure to adhere to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== Open Source Software

This project is built on the hard work of countless open source contributors.
Several of these projects are enumerated below.

* {Asciidoctor_}
* {ESPHome}
* {Git}

== Code of Conduct

Refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct] for details.

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3], a copy of which is provided in the link:LICENSE.adoc[license file].

© 2022 Jordan Williams

== Authors

mailto:{email}[{author}]
