esphome:
  name: cloudfree-smart-bulb-1

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret cloudfree_smart_bulb_api_encryption_key

ota:
  password: !secret cloudfree_smart_bulb_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${node_name} Fallback Hotspot"
    password: !secret cloudfree_smart_bulb_wifi_ap_password

captive_portal:

light:
  - platform: rgbct
    name: "Living Room Lamp"
    red: output_component1
    green: output_component2
    blue: output_component3
    color_temperature: output_component4
    white_brightness: output_component5
    cold_white_color_temperature: 153 mireds
    warm_white_color_temperature: 370 mireds

output:
  - platform: esp8266_pwm
    id: output_component1
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_component2
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_component3
    pin: GPIO14
  - platform: esp8266_pwm
    id: output_component4
    pin: GPIO5
  - platform: esp8266_pwm
    id: output_component5
    pin: GPIO13
