substitutions:
  node_name: cloudfree-smart-plug-v2-1
  node_description: Smart outlet used to control and monitor the Christmas tree lights
  friendly_name: Christmas Tree
  static_ip: 10.1.0.70

packages:
  aoycocr-x10s: !include common/aoycocr_x10s.yaml
  static-network: !include common/static_network.yaml

esphome:
  name: ${node_name}
  comment: ${node_description}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "CF-SP-v2-1 Fallback Hotspot"
    password: !secret cloudfree_smart_plug_v2_1_wifi_ap_password

captive_portal:

# Enable Home Assistant API
api:
  encryption:
    key: !secret cloudfree_smart_plug_v2_1_api_encryption_key

# Enable OTA updates
ota:
  password: !secret cloudfree_smart_plug_v2_1_ota_password
