substitutions:
  node_name: cloudfree-smart-plug-v2-2
  node_description: Smart outlet used to control and monitor the Guest Room lamp
  friendly_name: Guest Room Lamp
  static_ip: 192.168.1.71

packages:
  aoycocr-x10s: !include common/aoycocr_x10s.yaml
  static-network: !include common/static_network.yaml

esphome:
  name: ${node_name}
  comment: ${node_description}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "CF-SP-v2-2 Fallback Hotspot"
    password: !secret cloudfree_smart_plug_v2_2_wifi_ap_password

captive_portal:

# Enable Home Assistant API
api:
  encryption:
    key: !secret cloudfree_smart_plug_v2_2_api_encryption_key

# Enable OTA updates
ota:
  password: !secret cloudfree_smart_plug_v2_2_ota_password
