substitutions:
  node_name: environment-sensor
  static_ip: 10.1.0.53

packages:
  static-network: !include common/static_network.yaml

esphome:
  name: ${node_name}
  platformio_options:
    board_build.mcu: esp32c3
    board_build.variant: esp32c3
# platform:
# - https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream
# platform_packages:
# - framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.2

esp32:
  board: esp32dev
  variant: esp32c3
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret environment_sensor_api_encryption_key

ota:
  password: !secret environment_sensor_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Env Sensor Fallback Hotspot"
    password: !secret environment_sensor_wifi_ap_password

# captive_portal:

# light:
#   - platform: neopixelbus
#     variant: WS2812
#     pin: GPIO8
#     type: BGR
#     num_leds: 1
#     name: "Onboard RGB LED"
#     effects:
#       - random:
#       - pulse:
#       - strobe:
#       - flicker:

i2c:
  sda: GPIO4
  scl: GPIO5

sensor:
  - platform: bme680
    address: 0x77
    temperature:
      name: "Temperature"
      oversampling: 16x
    pressure:
      name: "Pressure"
    humidity:
      name: "Humidity"
      id: humidity
    gas_resistance:
      name: "Gas Resistance"
      id: gas_resistance
  - platform: template
    name: "Indoor Air Quality"
    id: iaq
    unit_of_measurement: IAQ
    lambda: 'return log(id(gas_resistance).state) + 0.04 * id(humidity).state;'
