substitutions:
  name: esp32-s3-box-3-01
  static_ip: 10.3.0.80
  friendly_name: ESP32 S3 Box 3 01

packages:
  static-network: !include
    file: common/static_network.yaml
  device_base:
    url: https://github.com/esphome/firmware
    ref: main
    files: [wake-word-voice-assistant/esp32-s3-box-3.yaml]
    refresh: 1d

api:
  encryption:
    key: !secret esp32_s3_box_3_01_api_encryption_key

ota:
  - platform: esphome
    password: !secret esp32_s3_box_3_01_ota_esphome_password

wifi:
  enable_btm: true
  enable_rrm: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${name} Fallback"
    password: !secret esp32_s3_box_3_01_wifi_ap_password
