substitutions:
  node_name: funhouse
  static_ip: 10.1.0.50

packages:
  static-network: !include common/static_network.yaml

esphome:
  name: ${node_name}
  platformio_options:
    board_build.mcu: esp32s2
    board_build.variant: esp32s2
# platform:
# - https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream
# platform_packages:
# - framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.2

esp32:
  board: esp32dev
  variant: esp32s2
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret funhouse_api_encryption_key

ota:
  password: !secret funhouse_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${node_name} Fallback Hotspot"
    password: !secret funhouse_wifi_ap_password

# captive_portal:

i2c:
  sda: GPIO34
  scl: GPIO33

sensor:
  - platform: mcp9808
    name: "Temperature"
    id: temperature_sensor

# esp32_touch:
#   setup_mode: false

binary_sensor:
  - platform: gpio
    pin: GPIO16
    name: "PIR Sensor"
    device_class: motion
  - platform: gpio
    name: "Button Up"
    pin:
      number: GPIO5
      # inverted: true
      mode:
        input: true
        # pullup: true
    filters:
      - delayed_on_off: 100ms
  - platform: gpio
    name: "Button Select"
    pin:
      number: GPIO4
      # inverted: true
      mode:
        input: true
        # pullup: true
    filters:
      - delayed_on_off: 100ms
  - platform: gpio
    name: "Button Down"
    pin:
      number: GPIO3
      # inverted: true
      mode:
        input: true
        # pullup: true
    filters:
      - delayed_on_off: 100ms
# - platform: esp32_touch
#   name: "Capacitive Touch 6"
#   pin: GPIO6
#   threshold: 20000
# - platform: gpio
#   pin:
#     number: GPIO7
#     mode:
#       input: true
#       pullup: true
#     inverted: true
#   name: "Capacitive Touch 7"
# - platform: gpio
#   pin:
#     number: GPIO8
#     mode:
#       input: true
#       pullup: true
#     inverted: true
#   name: "Capacitive Touch 8"
# - platform: gpio
#   pin:
#     number: GPIO9
#     mode:
#       input: true
#       pullup: true
#     inverted: true
#   name: "Capacitive Touch 9"
# - platform: gpio
#   pin:
#     number: GPIO10
#     mode:
#       input: true
#       pullup: true
#     inverted: true
#   name: "Capacitive Touch 10"
# - platform: gpio
#   pin:
#     number: GPIO11
#     mode:
#       input: true
#       pullup: true
#     inverted: true
#   name: "Capacitive Touch 11"
# - platform: esp32_touch
#   name: "Capacitive Touch 12"
#   pin: GPIO12
#   threshold: 20000

status_led:
  pin: GPIO37

# light:
#   - platform: neopixelbus
#     chipset: DOTSTAR
#     data_pin: GPIO14
#     clock_pin: GPIO15
#     num_leds: 5
#     rgb_order: BRG
#     name: "Dotstars"

# spi:
#   clk_pin: GPIO36
#   mosi_pin: GPIO35

# font:
#   - file: "FreeMono.ttf"
#     id: my_font
#     size: 20

# display:
#   - platform: st7735
#     model: "INITR_18BLACKTAB"
#     reset_pin: GPIO41
#     cs_pin: GPIO40
#     dc_pin: GPIO39
#     rotation: 0
#     col_start: 0
#     row_start: 0
#     device_width: 240
#     device_height: 240
#     eight_bit_color: true
#     lambda: |-
#       it.printf(0, 0, id(my_font), "The sensor value is: %.1f", id(temperature_sensor).state);

# output:
#   - platform: esp32_dac
#     pin: GPIO42
#     id: dac_output
