substitutions:
  node_name: humidity-sensor
  static_ip: 192.168.1.55

packages:
  static-network: !include common/static_network.yaml

esphome:
  name: ${node_name}
  platformio_options:
    board_build.mcu: esp32c3
    board_build.variant: esp32c3

esp32:
  board: esp32dev
  variant: esp32c3
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret humidity_sensor_api_encryption_key

ota:
  password: !secret humidity_sensor_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${node_name} Fallback Hotspot"
    password: !secret humidity_sensor_wifi_ap_password

# captive_portal:

i2c:
  sda: GPIO5
  scl: GPIO6

sensor:
  - platform: sht4x
    temperature:
      name: "Temperature"
    humidity:
      name: "Relative Humidity"
