substitutions:
  node_name: pressure-sensor
  static_ip: 10.1.0.51

packages:
  static-network: !include common/static_network.yaml

esphome:
  name: ${node_name}

esp32:
  board: tinypico
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret pressure_sensor_api_encryption_key

ota:
  password: !secret pressure_sensor_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${node_name} Fallback Hotspot"
    password: !secret pressure_sensor_wifi_ap_password

captive_portal:

light:
  - platform: fastled_spi
    chipset: APA102
    data_pin: GPIO2
    clock_pin: GPIO12
    rgb_order: BGR
    num_leds: 1
    name: "Onboard RGB LED"
    effects:
      - random:
      - pulse:
      - strobe:
      - flicker:

i2c:

sensor:
  - platform: bmp3xx
    temperature:
      name: "Temperature"
      oversampling: 16x
    pressure:
      name: "Pressure"
