name: Build
"on":
  pull_request:
    paths:
      - .github/workflows/build.yaml
      - esphome/**.yaml
      - esphome/**.yml
      - esphome/secrets.yaml.template
  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yaml
      - esphome/**.yaml
      - esphome/**.yml
      - esphome/secrets.yaml.template
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # todo Build using aarch64 when supported in ESP-IDF.
        arch:
          - amd64
        # - arm64
        node:
          - esp32-s3-box-3-01
    steps:
      - uses: actions/checkout@v4
      - run: |
          touch esphome/secrets.yaml
          echo 'wifi_ssid: "Test WiFi SSID"' >> esphome/secrets.yaml
          echo 'wifi_password: "Test WiFi Password"' >> esphome/secrets.yaml
          printf 'esp32_s3_box_3_01_wifi_ap_password: "%s"\n' "$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32 ; echo '')" >> esphome/secrets.yaml
          printf 'esp32_s3_box_3_01_ota_esphome_password: "%s"\n' "$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32 ; echo '')" >> esphome/secrets.yaml
          echo 'esp32_s3_box_3_01_api_encryption_key: "NKnCdo4g9aBF30g1S1e7Gkcm0d+3OK7zik/Ni2VPFyk="' >> esphome/secrets.yaml
      - uses: esphome/build-action@v6
        id: esphome-build
        with:
          yaml-file: esphome/${{ matrix.node }}.yaml
