name: CI
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        # todo Build using aarch64 when supported in ESP-IDF.
        arch:
          - amd64
        # - arm64
        node:
          - cloudfree_smart_plug_v2_1
          - cloudfree_smart_plug_v2_2
          - environment_sensor
          - funhouse
          - humidity_sensor
          - pressure_sensor
    steps:
      - uses: actions/checkout@v2
      - run: |
          touch esphome/secrets.yaml
          echo 'wifi_ssid: "Test WiFi SSID"' >> esphome/secrets.yaml
          echo 'wifi_password: "Test WiFi Password"' >> esphome/secrets.yaml
          echo 'wifi_ap_password: "Test Fallback Hotspot Password"' >> esphome/secrets.yaml
          echo 'ota_password: "Test OTA Update Password"' >> esphome/secrets.yaml
      - uses: esphome/build-action@v1
        id: esphome-build
        with:
          yaml_file: esphome/${{ matrix.node }}.yaml
